site_name: Sentiment Trading

repo_url: https://github.com/moerv9/sentiment
repo_name: moerv9/sentiment

theme: 
  name: material
  palette: 
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes


markdown_extensions:
  - tables

nav:
  - Getting Started: index.md

  - Notebooks: 
    - 'Get Tweets from Elon Musk' : 'jupyter_notebooks/getElonsTweets.ipynb'
    - 'Get Tweets for Hashtag' : 'jupyter_notebooks/getTweets.ipynb'
  - Approach: 
    - 'Introduction' : 'approach/Introduction.md'
    - 'Find the right Cryptocurrency' : 'approach/Coins.ipynb'
    - 'Social Media Analysis' : 'approach/SocialMedia.ipynb'
  - Helpful:
    - 'Dependencies' : dependencies.md
    - 'Commands List' : 'jupyter_notebooks/SavedCodeSnippets.ipynb'
  #- About:

plugins:
  - search
  - mkdocs-jupyter:
      theme: dark
      execute: True



# Link: https://squidfunk.github.io/mkdocs-material/