site_name: Sentiment Trading

repo_url: https://github.com/moerv9/sentiment
repo_name: moerv9/sentiment
edit_uri: ""

theme: 
  name: material
  palette: 
    scheme: slate
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  #- navigation.tracking #anchor tracking in url
  - navigation.expand #expands subsections
  - toc.follow
  - toc.integrate

#https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  

markdown_extensions:
  - tables
  - meta 

nav:
  - Getting Started: index.md

  - Notebooks: 
    - 'Get Tweets from Elon Musk' : 'jupyter_notebooks/getElonsTweets.ipynb'
    - 'Get Tweets for Hashtag' : 'jupyter_notebooks/getTweets.ipynb'
  - Approach: 
    - 'Introduction' : 'approach/Introduction.md'
    - 'Find the right Cryptocurrency' : 'approach/Coins.ipynb'
    - 'Social Media Analysis' : 'approach/SocialMedia.ipynb'
    - 'Sentiment Analysis' : 'approach/Sentiment.ipynb'
  - Helpful:
    - 'Dependencies' : dependencies.md
    - 'Commands List' : 'jupyter_notebooks/SavedCodeSnippets.ipynb'
  #- About:

plugins:
  - search
  - mkdocs-jupyter:
      theme: dark
      execute: True
      include_source: True



# Link: https://squidfunk.github.io/mkdocs-material/